### ISSUE TITLE
Some SVG links do not work; corruptor does it to search icon instead

### ISSUE THREAD

**Issue by logoffon** [x8BitRain/svg-emoji-corrupt#16]
![msedge_2022-07-14_22-57-38](https://user-images.githubusercontent.com/7828523/179026374-7a8a25fe-4111-478b-b93f-98025fd14146.gif)
See the gif and look closely at the search icon. The corruptor simply fails to load the SVG from Logopedia (without any indications) and any corruption settings does it to the search icon instead.

**Comment by x8BitRain** [comment]
This appears to be a new problem, I might look into it while I have time. You can always copy and paste the markup of the SVG directly into the URL box and it will work like so:

https://user-images.githubusercontent.com/15372551/179029567-80e54e17-fe97-400b-9bec-75c826b12100.mp4

**Comment by x8BitRain** [comment]
So not all SVG links work due to [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) issues which is a notoriously hard issue to get around. 

For example this link won't work
https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/acid.svg

But this one will 
https://upload.wikimedia.org/wikipedia/commons/4/4f/SVG_Logo.svg

It just depends on the host, so I recommend either first downloading and uploading the SVG or pasting the markup of the SVG into the URL input and it should work then.
